#!/bin/bash

#SBATCH --ntasks-per-node=40
#SBATCH --nodes=1
#SBATCH --time=48:00:00          # walltime
#SBATCH -p gpu
#SBATCH --gres=gpu:1

module purge
module load hdf5/1.10.2/gcc/parallel
module load gcc
module load cuda
module load nvhpc

mpirun -np 4 ./main
